# Generated by Django 5.2.7 on 2026-01-05 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'groups__name': 'patients'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_practitioners', to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(limit_choices_to={'groups__name': 'practitioners'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('practitioner', 'patient')},
            },
        ),
    ]
