# Generated by Django 5.2.7 on 2026-01-22 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_practitionerpatient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked')], default='GRANTED', max_length=16)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'groups__name': 'patients'}, on_delete=django.db.models.deletion.CASCADE, related_name='consents_as_patient', to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(limit_choices_to={'groups__name': 'practitioners'}, on_delete=django.db.models.deletion.CASCADE, related_name='consents_as_practitioner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'practitioner')},
            },
        ),
    ]
